config/routes.rb
Rightinsure::Application.routes.draw do
  get "dashboard/index"
  devise_for :users
  root "home#index"
  get "home/index"
  get "home/aboutus"
  namespace :admin do
    root "dashboard#index"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role
  include Mongoid::Document
  
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
  
  field :name, :type => String
  index({ :name => 1 }, { :unique => true })


  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})
  
  scopify
end

app/models/user.rb
class User
  include Mongoid::Document
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aboutus
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/dashboard/index.html.erb
<div class="page-header">
  <h1>Admin::Dashboard#index</h1>
</div>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/home/aboutus.html.erb
<section class="breadcrumbs">
  <div class="container">
    <div class="page-header">
      <div class="row">
        <div class="col-md-8">
          <h1>About Us<small> : need help, support or advise?</small></h1>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="container">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="gmap">
          <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=&amp;daddr=%E0%B8%96%E0%B8%99%E0%B8%99%E0%B9%82%E0%B8%8A%E0%B8%84%E0%B8%8A%E0%B8%B1%E0%B8%A2+4&amp;hl=th&amp;geocode=FZvy0gAdX-7-BQ&amp;sll=13.823328,100.596013&amp;sspn=0.018586,0.033023&amp;mra=ls&amp;ie=UTF8&amp;ll=13.823328,100.596013&amp;spn=0.018586,0.033023&amp;t=m&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=d&amp;source=embed&amp;saddr=&amp;daddr=%E0%B8%96%E0%B8%99%E0%B8%99%E0%B9%82%E0%B8%8A%E0%B8%84%E0%B8%8A%E0%B8%B1%E0%B8%A2+4&amp;hl=th&amp;geocode=FZvy0gAdX-7-BQ&amp;sll=13.823328,100.596013&amp;sspn=0.018586,0.033023&amp;mra=ls&amp;ie=UTF8&amp;ll=13.823328,100.596013&amp;spn=0.018586,0.033023&amp;t=m" style="color:#0000FF;text-align:left">ดูแผนที่ขนาดใหญ่ขึ้น</a></small>
        </div>
      </div>
    </div>
    <div class="row">
      <section class="pull-left col-md-8" id="page-sidebar">
        <form action="#" method="post">
          <fieldset>
            <legend><h3> Leave Your Message </h3> </legend>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="yourname"> YourName: </label>
                  <input type="text" class="form-control" id="yourname" name="yourname" placeholder="your name">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="email"> Email: </label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="email">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="message"> Message: </label>
                  <textarea class="form-control" rows="10"  id="message" name="message" placeholder="message"></textarea>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <input id="submit_btn" class="form-button btn btn-primary btn-large" type="submit" value="Send Message!" name="submit">
              </div>
            </div>
          </fieldset>
        </form>
        <hr />
      </section>
      <!--sidebar-->
      <aside class="pull-right col-md-4" id="sidebar">
        <!--address-->
        <section>
          <h3>Address</h3>
          <address>
            <p>
            <i class="fa fa-map-marker fa-fw"></i> Street Name 432/2, London, 90210<br>
            <i class="fa fa-phone fa-fw"></i> (123) 456-7890<br>
            <i class="fa fa-mobile fa-fw"></i> (123) 456-7890<br>
            <i class="fa fa-envelope fa-fw"></i> <a href="mailto:#">info@email.com</a>
            </p>
          </address>
        </section>
        <section>
          <h3>Business Hour</h3>
          <ul class="unstyled">
            <li class="clearfix">Monday - Fiyday:<p class="pull-right">9 am  to 6 pm</p></li>
            <li class="clearfix">Saturday:<p class="pull-right">10 am  to 4 pm</p></li>
            <li class="clearfix">Sunday:<p class="pull-right">Closed</p></li>
          </ul>
        </section>
      </aside>
    </div>
  </div>    
</section>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <p> <%= image_tag "right/rightlogosmall.png" %></p>
      <address>
        <p><i class="fa fa-map-marker fa-fw"></i> Street Name 432/2, London, 90210</p>
        <p><i class="fa fa-phone fa-fw"></i> (123) 456-7890</p>
        <p><i class="fa fa-mobile fa-fw"></i> (123) 456-7890</p>
        <p><i class="fa fa-envelope fa-fw"></i> <a href="mailto:#">info@email.com</a></p>
      </address>
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-8">

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <p class="heading">About Us</p>
      <p>Curabitur suscipit ultricies metus quis scelerisque. Quisque eget enim orci. Cras sagittis volutpat auctor. </p>
      <p class="heading">Subscribe</p>
      <p>Keep updated with our news. Your email is safe with us!</p>
      <div class="input-append">
        <input type="text" placeholder="Enter Email Address" class="span2"/>
        <button type="button" class="btn btn-inverse">Subscribe!</button>
      </div>
    </div>
    <div class="col-md-4">
      <p class="heading">Company</p>
      <ul class="footer-navigate">
        <li><a href="./index.html">Home</a></li>
        <li><a href="./about.html">About</a></li>
        <li><a href="./portfolio4.html">Portfolio</a></li>
        <li><a href="./blog-sidebar-right.html">Blog</a></li>
        <li><a href="./services.html">Service</a></li>
      </ul>
    </div>
  </div>
</div> 

app/views/layouts/_footer_menu.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <p class="copyright">&copy; Copyright 2012. Powered by <a href="http://dxthemes.com/">DX Themes</a>.</p>
    </div>
    <div class="col-md-8 hidden-phone">
      <ul class="pull-right">
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">Sitemap</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default bs-docs-nav" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<i class="fa fa-home fa-fw"></i>'.html_safe, root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <ul class="nav pull-right">   
        <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
          <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
          </li>
          <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
          </li>
          <li class="divider"></li>
          <% if user_signed_in? %>
            <li><%= link_to '<i class="fa fa-sign-out fa-fw"></i>Sign out'.html_safe, destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to '<i class="fa fa-sign-in fa-fw"></i> Sign in'.html_safe, new_user_session_path %></li>
            <li><%= link_to '<i class="fa fa-sign-in fa-fw"></i> Sign up'.html_safe, new_user_registration_path %></li>
          <% end %>
        </ul>
        <!-- /.dropdown-user -->
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="active"><a href="#">home</a></li>
<li><a href="#">Service</a></li>
<li><%= link_to '<i class="fa fa-phone-square fa-fw"></i> About Us'.html_safe, home_aboutus_path %></li>
<li>
  <form class="navbar-form">
    <input type="text"  placeholder="Search in ..." id="searchInput" />  
    <button type="submit" class"btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
  </form>
</li>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rightinsure" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rightinsure" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="admin">
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="center"> <%= image_tag "right/rightlogosmall.png" %> </li>
              <li class="sidebar-brand"><a href="#"><h3> Admin Area </h3> </a>
                </li>
                <li><a href="#">Dashboard</a>
                </li>
                <li><a href="#">Shortcuts</a>
                </li>
                <li><a href="#">Overview</a>
                </li>
                <li><a href="#">Events</a>
                </li>
                <li><a href="#">About</a>
                </li>
                <li><a href="#">Services</a>
                </li>
                <li><a href="#">Contact</a>
                </li>
            </ul>
        </div>

        <!-- Page content -->
        <div id="page-content-wrapper">
            <div class="content-header">
                <h1>
                    <a id="menu-toggle" href="#" class="btn btn-default"><i class="icon-reorder"></i></a>
                    Simple Sidebar
                </h1>
            </div>
            <!-- Keep all page content within the page-content inset div! -->
            <div class="page-content inset">
                <div class="row">
                  <div class="col-md-12">
                    <p class="lead">This simple sidebar template has a hint of JavaScript to make the template responsive. It also includes Font Awesome icon fonts.</p>
                    <%= yield %>
                  </div>
                  <div class="col-md-6">
                        <p class="well">The template still uses the default Bootstrap rows and columns.</p>
                    </div>
                    <div class="col-md-6">
                        <p class="well">But the full-width layout means that you wont be using containers.</p>
                    </div>
                    <div class="col-md-4">
                        <p class="well">Three Column Example</p>
                    </div>
                    <div class="col-md-4">
                        <p class="well">Three Column Example</p>
                    </div>
                    <div class="col-md-4">
                        <p class="well">You get the idea! Do whatever you want in the page content area!</p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
    });
    </script>
  </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rightinsure" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rightinsure" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <%= image_tag 'right/rightlogo.png' %>
        </div>
        <div class="col-sm-4">

        </div>

        <div class="col-sm-4">
          <%= image_tag 'right/callcenter.png' %>

        </div>
      </div>
    </div> <!--end containner -->
  <header class="navbar navbar-inverse  bs-docs-nav" role="banner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <div class="carousel slide" id="myCarousel">

    </div> <!-- end myCarousel -->
    <div class="row" id="bigCallout">

    </div> <!-- end bigCallout-->
    <div class="row" id="featuresHeading">

    </div> <!--end of featuresHeading-->
  </div>
  <footer id="footer">
       <%= render 'layouts/footer' %>
  </footer>
  <section id="footer-menu">
    <%= render 'layouts/footer_menu' %>
  </section>
  </body>
  </html>